# Imports

In [1]:
from __future__ import annotations

import numpy as np

import torch
import matplotlib.pyplot as plt
import pandas


# pytorch with gpu
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("GPU is available and being used")
else:
    device = torch.device("cpu")
    print("GPU is not available, using CPU instead")

GPU is available and being used


# 1. Pytorch Tensors
### 1.1 What is a `Tensor`?
- Usually a multi-dimensional matrix of numbers used within a neural network.
- Used as the input, output and operations within a neural network.
- Supports matrix operations, e.g.:


$\sigma\Bigg(\begin{bmatrix}
    w_{11} & w_{12} & \dots & w_{1n} \\
    w_{21} & w_{22} & \dots & w_{2n} \\
    \vdots & \vdots &       & \vdots \\
    w_{m1} & w_{m2} & \dots & w_{mn}
\end{bmatrix}
\begin{bmatrix}
    x_1 \\ x_2 \\ \vdots \\ x_n
\end{bmatrix}
+
\begin{bmatrix}
    b_1 \\ b_2 \\ \vdots \\ b_m
\end{bmatrix}\Bigg)
$

### 1.2 Creating Tensors
- Created using `torch.tensor(args)`,
- Can be instantiated with a multi-dimensional iterable/single digit

In [9]:
# scalars (tensor with a single digit)
scalar = torch.tensor(7)
print(f'A scalar has {scalar.ndim} dimensions')

# vectors (single-dimension set of numbers)
vector = torch.tensor([7, 7, 7])
print(f'A vector has {vector.ndim} dimensions')

# matrices (2-dimensional set of numbers)
matrix = torch.tensor([[7, 7, 7],
                       [8, 8, 8],
                       [9, 9, 9]])
print(f'A matrix has {matrix.ndim} dimensions')

# tensor (n-dimensional set of numbers)
tensor = torch.tensor([[[1, 2, 3],
                        [3, 4, 5],
                        [7, 8, 9]],
                       [[10, 11, 12],
                        [13, 14, 15],
                        [16, 17, 18]]])
print(f'A tensor has {tensor.ndim} dimensions')

A scalar has 0 dimensions
A vector has 1 dimensions
A matrix has 2 dimensions
A tensor has 3 dimensions


### 1.3 Creating Tensors Easily
- Usually tensors wont be hand-crafted like above.
- This is handled by PyTorch, with just a tensor shape passed instead of a set of numbers.
  
#### 1.3.1 Random Tensors
- Many neural networks start with tensors (weight and biases) of random numbers which are then adjusted to better represent the data.
- A model starts with random numbers, looks at the data and updates it's random numbers, then rinse and repeat

In [16]:
# create a random tensor of size (3, 4)
rand_tensor = torch.rand((3, 4))
print(rand_tensor)
print(f'\nRandom tensor has size {rand_tensor.size()} and {rand_tensor.ndim} dimensions.')

tensor([[0.5232, 0.1631, 0.0053, 0.6401],
        [0.5238, 0.4184, 0.3917, 0.7943],
        [0.2628, 0.6098, 0.6061, 0.8116]])

Random tensor has size torch.Size([3, 4]) and 2 dimensions.


In [27]:
# Create a random tensor with a similar size to an image tensor (RGB)
image_height, image_width, image_channels = 224, 224, 3
random_image_tensor = torch.rand((image_channels, image_height, image_width))
print(random_image_tensor)
print(f'\nRandom image-like tensor has size {random_image_tensor.size()} and {random_image_tensor.ndim} dimensions.')

tensor([[[0.8821, 0.5698, 0.7690,  ..., 0.7400, 0.6329, 0.0469],
         [0.9483, 0.8512, 0.1780,  ..., 0.2340, 0.2860, 0.5788],
         [0.4873, 0.3177, 0.9980,  ..., 0.6192, 0.4665, 0.7580],
         ...,
         [0.8261, 0.7206, 0.9057,  ..., 0.8470, 0.7275, 0.0701],
         [0.5064, 0.6404, 0.6958,  ..., 0.4322, 0.2770, 0.1885],
         [0.9849, 0.6889, 0.8576,  ..., 0.4625, 0.9247, 0.4965]],

        [[0.5306, 0.0555, 0.7050,  ..., 0.1257, 0.0675, 0.3636],
         [0.3453, 0.6845, 0.6131,  ..., 0.9631, 0.4905, 0.2727],
         [0.2349, 0.3009, 0.1962,  ..., 0.5244, 0.4280, 0.8909],
         ...,
         [0.7612, 0.3707, 0.1354,  ..., 0.4863, 0.6554, 0.4142],
         [0.1923, 0.5089, 0.0924,  ..., 0.7655, 0.8265, 0.0790],
         [0.9362, 0.2015, 0.3908,  ..., 0.3229, 0.3648, 0.7773]],

        [[0.3332, 0.7869, 0.9964,  ..., 0.7411, 0.1448, 0.3091],
         [0.4049, 0.0919, 0.7072,  ..., 0.0174, 0.9662, 0.8420],
         [0.2060, 0.4405, 0.1335,  ..., 0.2078, 0.3851, 0.

#### 1.3.2 Filled Tensors
- Tensors of all $0$ s or $1$ s
- Useful when creating `masks`, e.g.:

$\begin{bmatrix}
    w_{11} & w_{12} & \dots & w_{1n} \\
    w_{21} & w_{22} & \dots & w_{2n} \\
    \vdots & \vdots &       & \vdots \\
    w_{m1} & w_{m2} & \dots & w_{mn}
\end{bmatrix}
\begin{bmatrix}
    0 & 0 & \dots & 0 \\
    0 & 0 & \dots & 0 \\
    \vdots & \vdots & & \vdots \\
    0 & 0 & \dots & 0
\end{bmatrix} = \begin{bmatrix}
    0 & 0 & \dots & 0 \\
    0 & 0 & \dots & 0 \\
    \vdots & \vdots & & \vdots \\
    0 & 0 & \dots & 0
\end{bmatrix}$<br>
- to ignore an entire tensor of numbers


In [31]:
# tensor of 0s
zeros_tensor = torch.zeros((3, 4))
print(zeros_tensor)

# tensor of 1s
ones_tensor = torch.ones((3, 4))
print(ones_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
